# Generated by Django 5.0.4 on 2024-04-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_otp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
