version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    command: "python backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
