version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    command: "python backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:14.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  pg_data:
