version: '3'
services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    command: "python backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:14.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  pg_data:
